auteur = "Kim Blanchard"
bloctexte = "justify"
copyright = "CC BY-NC-SA"
couverture = "/images/Logo_print.png"
description = "Description"
edition = "Fabrique"
format = "portrait"
indentation = "oui"
isbn = ""
licence = "CC BY-NC-SA"
logo = "images/Logo.png"
marques = "crop"
mention = "Fabrique"
quatrieme = "oui"
readingtime = "oui"
search = false
soustitre = "Recueil de textes"
titre = "Carnet d'écriture"
